// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: admin.entity.proto

package rbac_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id"`
	// @gotags: json:"status"
	Status int64 `protobuf:"varint,5,opt,name=Status,proto3" json:"status"`
}

func (x *AdminCreateReq) Reset() {
	*x = AdminCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateReq) ProtoMessage() {}

func (x *AdminCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateReq.ProtoReflect.Descriptor instead.
func (*AdminCreateReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{0}
}

func (x *AdminCreateReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminCreateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AdminCreateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	// @gotags: json:"password"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password"`
	// @gotags: json:"domain_id"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id"`
	// @gotags: json:"status"
	Status int64 `protobuf:"varint,5,opt,name=Status,proto3" json:"status"`
}

func (x *AdminUpdateReq) Reset() {
	*x = AdminUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateReq) ProtoMessage() {}

func (x *AdminUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUpdateReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AdminUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminUpdateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AdminUpdateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	// @gotags: form:"name"
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
	// @gotags: form:"status"
	Status int64 `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty" form:"status"`
	// @gotags: form:"account"
	Account string `protobuf:"bytes,6,opt,name=Account,proto3" json:"Account,omitempty" form:"account"`
	// @gotags: form:"sort_field"
	SortField string `protobuf:"bytes,7,opt,name=SortField,proto3" json:"SortField,omitempty" form:"sort_field"`
	// @gotags: form:"sort_order" binding:"oneof='' asc desc,required_with=SortField"
	SortOrder string `protobuf:"bytes,8,opt,name=SortOrder,proto3" json:"SortOrder,omitempty" form:"sort_order" binding:"oneof='' asc desc,required_with=SortField"`
}

func (x *AdminListReq) Reset() {
	*x = AdminListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListReq) ProtoMessage() {}

func (x *AdminListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListReq.ProtoReflect.Descriptor instead.
func (*AdminListReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{2}
}

func (x *AdminListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminListReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AdminListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminListReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminListReq) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *AdminListReq) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type AdminDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *AdminDelReq) Reset() {
	*x = AdminDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDelReq) ProtoMessage() {}

func (x *AdminDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDelReq.ProtoReflect.Descriptor instead.
func (*AdminDelReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDelReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AdminDelReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"password" binding:"required"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	// @inject_tag: json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	// @inject_tag: json:"data"
	Data *LoginResData `protobuf:"bytes,3,opt,name=Data,proto3" json:"data"`
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginRes) GetData() *LoginResData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginResData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"uid"
	UID int64 `protobuf:"varint,1,opt,name=UID,proto3" json:"uid"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	// @gotags: json:"role_ids"
	RoleIDs []int64 `protobuf:"varint,3,rep,packed,name=RoleIDs,proto3" json:"role_ids"`
}

func (x *LoginResData) Reset() {
	*x = LoginResData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResData) ProtoMessage() {}

func (x *LoginResData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResData.ProtoReflect.Descriptor instead.
func (*LoginResData) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResData) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *LoginResData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginResData) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *LoginResData) GetRoleIDs() []int64 {
	if x != nil {
		return x.RoleIDs
	}
	return nil
}

type AccountEditReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// @gotags: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	// @gotags: json:"-"
	DomainID int64 `protobuf:"varint,3,opt,name=DomainID,proto3" json:"-"`
	// @gotags: json:"-"
	UID int64 `protobuf:"varint,4,opt,name=UID,proto3" json:"-"`
}

func (x *AccountEditReq) Reset() {
	*x = AccountEditReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEditReq) ProtoMessage() {}

func (x *AccountEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEditReq.ProtoReflect.Descriptor instead.
func (*AccountEditReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{7}
}

func (x *AccountEditReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountEditReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountEditReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AccountEditReq) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type AdminMenuTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"-"
	RoleIDs []int64 `protobuf:"varint,1,rep,packed,name=RoleIDs,proto3" json:"RoleIDs,omitempty" form:"-"`
	// @gotags: form:"-"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"-"`
}

func (x *AdminMenuTreeReq) Reset() {
	*x = AdminMenuTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminMenuTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMenuTreeReq) ProtoMessage() {}

func (x *AdminMenuTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMenuTreeReq.ProtoReflect.Descriptor instead.
func (*AdminMenuTreeReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{8}
}

func (x *AdminMenuTreeReq) GetRoleIDs() []int64 {
	if x != nil {
		return x.RoleIDs
	}
	return nil
}

func (x *AdminMenuTreeReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type AdminRoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"domain_id"
	DomainID int64 `protobuf:"varint,1,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id"`
	// @gotags: form:"uid"
	UID int64 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty" form:"uid"`
}

func (x *AdminRoleListReq) Reset() {
	*x = AdminRoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleListReq) ProtoMessage() {}

func (x *AdminRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleListReq.ProtoReflect.Descriptor instead.
func (*AdminRoleListReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{9}
}

func (x *AdminRoleListReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AdminRoleListReq) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type AdminRoleSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"domain_id"
	DomainID int64 `protobuf:"varint,1,opt,name=DomainID,proto3" json:"domain_id"`
	// @gotags: json:"role_ids"
	RoleIDs []int64 `protobuf:"varint,2,rep,packed,name=RoleIDs,proto3" json:"role_ids"`
	// @gotags: json:"uid"
	UID int64 `protobuf:"varint,3,opt,name=UID,proto3" json:"uid"`
}

func (x *AdminRoleSetReq) Reset() {
	*x = AdminRoleSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRoleSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleSetReq) ProtoMessage() {}

func (x *AdminRoleSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleSetReq.ProtoReflect.Descriptor instead.
func (*AdminRoleSetReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{10}
}

func (x *AdminRoleSetReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

func (x *AdminRoleSetReq) GetRoleIDs() []int64 {
	if x != nil {
		return x.RoleIDs
	}
	return nil
}

func (x *AdminRoleSetReq) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

var File_admin_entity_proto protoreflect.FileDescriptor

var file_admin_entity_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x62, 0x61, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8e, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x84, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xdc, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x72,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x22, 0x40, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x5d, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x6a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x22, 0x6e,
	0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x22, 0x48,
	0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x0f, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x55, 0x49, 0x44, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x72, 0x62, 0x61, 0x63,
	0x5f, 0x70, 0x62, 0x3b, 0x72, 0x62, 0x61, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_admin_entity_proto_rawDescOnce sync.Once
	file_admin_entity_proto_rawDescData = file_admin_entity_proto_rawDesc
)

func file_admin_entity_proto_rawDescGZIP() []byte {
	file_admin_entity_proto_rawDescOnce.Do(func() {
		file_admin_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_entity_proto_rawDescData)
	})
	return file_admin_entity_proto_rawDescData
}

var file_admin_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_admin_entity_proto_goTypes = []interface{}{
	(*AdminCreateReq)(nil),   // 0: rbacProto.AdminCreateReq
	(*AdminUpdateReq)(nil),   // 1: rbacProto.AdminUpdateReq
	(*AdminListReq)(nil),     // 2: rbacProto.AdminListReq
	(*AdminDelReq)(nil),      // 3: rbacProto.AdminDelReq
	(*LoginReq)(nil),         // 4: rbacProto.LoginReq
	(*LoginRes)(nil),         // 5: rbacProto.LoginRes
	(*LoginResData)(nil),     // 6: rbacProto.LoginResData
	(*AccountEditReq)(nil),   // 7: rbacProto.AccountEditReq
	(*AdminMenuTreeReq)(nil), // 8: rbacProto.AdminMenuTreeReq
	(*AdminRoleListReq)(nil), // 9: rbacProto.AdminRoleListReq
	(*AdminRoleSetReq)(nil),  // 10: rbacProto.AdminRoleSetReq
}
var file_admin_entity_proto_depIdxs = []int32{
	6, // 0: rbacProto.LoginRes.Data:type_name -> rbacProto.LoginResData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_entity_proto_init() }
func file_admin_entity_proto_init() {
	if File_admin_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountEditReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminMenuTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRoleSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_entity_proto_goTypes,
		DependencyIndexes: file_admin_entity_proto_depIdxs,
		MessageInfos:      file_admin_entity_proto_msgTypes,
	}.Build()
	File_admin_entity_proto = out.File
	file_admin_entity_proto_rawDesc = nil
	file_admin_entity_proto_goTypes = nil
	file_admin_entity_proto_depIdxs = nil
}
