// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.entity.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminCreateReq struct {
	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminCreateReq) Reset()         { *m = AdminCreateReq{} }
func (m *AdminCreateReq) String() string { return proto.CompactTextString(m) }
func (*AdminCreateReq) ProtoMessage()    {}
func (*AdminCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{0}
}

func (m *AdminCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminCreateReq.Unmarshal(m, b)
}
func (m *AdminCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminCreateReq.Marshal(b, m, deterministic)
}
func (m *AdminCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminCreateReq.Merge(m, src)
}
func (m *AdminCreateReq) XXX_Size() int {
	return xxx_messageInfo_AdminCreateReq.Size(m)
}
func (m *AdminCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminCreateReq proto.InternalMessageInfo

func (m *AdminCreateReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AdminCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminCreateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminCreateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type AdminUpdateReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	// @gotags: json:"password"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUpdateReq) Reset()         { *m = AdminUpdateReq{} }
func (m *AdminUpdateReq) String() string { return proto.CompactTextString(m) }
func (*AdminUpdateReq) ProtoMessage()    {}
func (*AdminUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{1}
}

func (m *AdminUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUpdateReq.Unmarshal(m, b)
}
func (m *AdminUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUpdateReq.Marshal(b, m, deterministic)
}
func (m *AdminUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUpdateReq.Merge(m, src)
}
func (m *AdminUpdateReq) XXX_Size() int {
	return xxx_messageInfo_AdminUpdateReq.Size(m)
}
func (m *AdminUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUpdateReq proto.InternalMessageInfo

func (m *AdminUpdateReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AdminUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminUpdateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminUpdateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type AdminListReq struct {
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	// @gotags: form:"name"
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminListReq) Reset()         { *m = AdminListReq{} }
func (m *AdminListReq) String() string { return proto.CompactTextString(m) }
func (*AdminListReq) ProtoMessage()    {}
func (*AdminListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{2}
}

func (m *AdminListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminListReq.Unmarshal(m, b)
}
func (m *AdminListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminListReq.Marshal(b, m, deterministic)
}
func (m *AdminListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminListReq.Merge(m, src)
}
func (m *AdminListReq) XXX_Size() int {
	return xxx_messageInfo_AdminListReq.Size(m)
}
func (m *AdminListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminListReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminListReq proto.InternalMessageInfo

func (m *AdminListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AdminListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type AdminDelReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDelReq) Reset()         { *m = AdminDelReq{} }
func (m *AdminDelReq) String() string { return proto.CompactTextString(m) }
func (*AdminDelReq) ProtoMessage()    {}
func (*AdminDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{3}
}

func (m *AdminDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDelReq.Unmarshal(m, b)
}
func (m *AdminDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDelReq.Marshal(b, m, deterministic)
}
func (m *AdminDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDelReq.Merge(m, src)
}
func (m *AdminDelReq) XXX_Size() int {
	return xxx_messageInfo_AdminDelReq.Size(m)
}
func (m *AdminDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDelReq proto.InternalMessageInfo

func (m *AdminDelReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AdminDelReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type LoginReq struct {
	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"password" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type LoginRes struct {
	// @inject_tag: json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	// @inject_tag: json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	// @inject_tag: json:"data"
	Data                 *LoginResData `protobuf:"bytes,3,opt,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{5}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginRes) GetData() *LoginResData {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginResData struct {
	// @gotags: json:"uid"
	UID int64 `protobuf:"varint,1,opt,name=UID,proto3" json:"uid"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	// @gotags: json:"role_ids"
	RoleIDs              []int64  `protobuf:"varint,3,rep,packed,name=RoleIDs,proto3" json:"role_ids"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResData) Reset()         { *m = LoginResData{} }
func (m *LoginResData) String() string { return proto.CompactTextString(m) }
func (*LoginResData) ProtoMessage()    {}
func (*LoginResData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{6}
}

func (m *LoginResData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResData.Unmarshal(m, b)
}
func (m *LoginResData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResData.Marshal(b, m, deterministic)
}
func (m *LoginResData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResData.Merge(m, src)
}
func (m *LoginResData) XXX_Size() int {
	return xxx_messageInfo_LoginResData.Size(m)
}
func (m *LoginResData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResData proto.InternalMessageInfo

func (m *LoginResData) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *LoginResData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResData) GetRoleIDs() []int64 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

type AdminMenuTreeReq struct {
	// @gotags: form:"-"
	RoleIDs []int64 `protobuf:"varint,1,rep,packed,name=RoleIDs,proto3" json:"RoleIDs,omitempty" form:"-"`
	// @gotags: form:"-"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminMenuTreeReq) Reset()         { *m = AdminMenuTreeReq{} }
func (m *AdminMenuTreeReq) String() string { return proto.CompactTextString(m) }
func (*AdminMenuTreeReq) ProtoMessage()    {}
func (*AdminMenuTreeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{7}
}

func (m *AdminMenuTreeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminMenuTreeReq.Unmarshal(m, b)
}
func (m *AdminMenuTreeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminMenuTreeReq.Marshal(b, m, deterministic)
}
func (m *AdminMenuTreeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminMenuTreeReq.Merge(m, src)
}
func (m *AdminMenuTreeReq) XXX_Size() int {
	return xxx_messageInfo_AdminMenuTreeReq.Size(m)
}
func (m *AdminMenuTreeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminMenuTreeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminMenuTreeReq proto.InternalMessageInfo

func (m *AdminMenuTreeReq) GetRoleIDs() []int64 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

func (m *AdminMenuTreeReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type AdminRoleListReq struct {
	// @gotags: from:"domain_id"
	DomainID int64 `protobuf:"varint,1,opt,name=DomainID,proto3" json:"DomainID,omitempty" from:"domain_id"`
	// @gotags: from:"role_id"
	RoleID               int64    `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty" from:"role_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRoleListReq) Reset()         { *m = AdminRoleListReq{} }
func (m *AdminRoleListReq) String() string { return proto.CompactTextString(m) }
func (*AdminRoleListReq) ProtoMessage()    {}
func (*AdminRoleListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{8}
}

func (m *AdminRoleListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRoleListReq.Unmarshal(m, b)
}
func (m *AdminRoleListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRoleListReq.Marshal(b, m, deterministic)
}
func (m *AdminRoleListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRoleListReq.Merge(m, src)
}
func (m *AdminRoleListReq) XXX_Size() int {
	return xxx_messageInfo_AdminRoleListReq.Size(m)
}
func (m *AdminRoleListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRoleListReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRoleListReq proto.InternalMessageInfo

func (m *AdminRoleListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

func (m *AdminRoleListReq) GetRoleID() int64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type AdminRoleSetReq struct {
	// @gotags: json:"domain_id"
	DomainID int64 `protobuf:"varint,1,opt,name=DomainID,proto3" json:"domain_id"`
	// @gotags: json:"role_ids"
	RoleIDs []int64 `protobuf:"varint,2,rep,packed,name=RoleIDs,proto3" json:"role_ids"`
	// @gotags: json:"admin_id"
	AdminID              int64    `protobuf:"varint,3,opt,name=AdminID,proto3" json:"admin_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRoleSetReq) Reset()         { *m = AdminRoleSetReq{} }
func (m *AdminRoleSetReq) String() string { return proto.CompactTextString(m) }
func (*AdminRoleSetReq) ProtoMessage()    {}
func (*AdminRoleSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc6671887c380a3, []int{9}
}

func (m *AdminRoleSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRoleSetReq.Unmarshal(m, b)
}
func (m *AdminRoleSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRoleSetReq.Marshal(b, m, deterministic)
}
func (m *AdminRoleSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRoleSetReq.Merge(m, src)
}
func (m *AdminRoleSetReq) XXX_Size() int {
	return xxx_messageInfo_AdminRoleSetReq.Size(m)
}
func (m *AdminRoleSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRoleSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRoleSetReq proto.InternalMessageInfo

func (m *AdminRoleSetReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

func (m *AdminRoleSetReq) GetRoleIDs() []int64 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

func (m *AdminRoleSetReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

func init() {
	proto.RegisterType((*AdminCreateReq)(nil), "proto.AdminCreateReq")
	proto.RegisterType((*AdminUpdateReq)(nil), "proto.AdminUpdateReq")
	proto.RegisterType((*AdminListReq)(nil), "proto.AdminListReq")
	proto.RegisterType((*AdminDelReq)(nil), "proto.AdminDelReq")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto.RegisterType((*LoginResData)(nil), "proto.LoginResData")
	proto.RegisterType((*AdminMenuTreeReq)(nil), "proto.AdminMenuTreeReq")
	proto.RegisterType((*AdminRoleListReq)(nil), "proto.AdminRoleListReq")
	proto.RegisterType((*AdminRoleSetReq)(nil), "proto.AdminRoleSetReq")
}

func init() { proto.RegisterFile("admin.entity.proto", fileDescriptor_6cc6671887c380a3) }

var fileDescriptor_6cc6671887c380a3 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xd9, 0x7e, 0x39, 0x2d, 0xb5, 0xac, 0x20, 0xc1, 0x53, 0xc9, 0xc5, 0x9e, 0x22, 0xe8,
	0x49, 0x3c, 0x55, 0x17, 0x31, 0x50, 0x8b, 0x6c, 0xed, 0x41, 0xf1, 0xb2, 0x6d, 0x96, 0x12, 0x68,
	0xb2, 0x31, 0x49, 0x15, 0xfd, 0xf5, 0xb2, 0xd3, 0x64, 0x49, 0xa4, 0x56, 0x04, 0x4f, 0x99, 0xb7,
	0xfb, 0xf2, 0xde, 0xcc, 0xdb, 0x01, 0x2a, 0x82, 0x28, 0x8c, 0x3d, 0x19, 0xe7, 0x61, 0xfe, 0xe1,
	0x25, 0xa9, 0xca, 0x15, 0x6d, 0xe2, 0xc7, 0x7d, 0x83, 0xfe, 0x58, 0x5f, 0xde, 0xa4, 0x52, 0xe4,
	0x92, 0xcb, 0x57, 0xea, 0x40, 0x7b, 0xbc, 0x5c, 0xaa, 0x4d, 0x9c, 0x3b, 0xd6, 0xd0, 0x1a, 0x1d,
	0xf0, 0x12, 0x52, 0x0a, 0x8d, 0xa9, 0x88, 0xa4, 0x63, 0xe3, 0x31, 0xd6, 0xf4, 0x04, 0x3a, 0x0f,
	0x22, 0xcb, 0xde, 0x55, 0x1a, 0x38, 0x04, 0xcf, 0x0d, 0xd6, 0x77, 0x4c, 0x45, 0x22, 0x8c, 0x7d,
	0xe6, 0x34, 0x86, 0xd6, 0x88, 0x70, 0x83, 0xdd, 0x75, 0xe1, 0x3b, 0x4f, 0x82, 0xc2, 0xb7, 0x0f,
	0xb6, 0xcf, 0xd0, 0x92, 0x70, 0xdb, 0x67, 0xff, 0xea, 0x16, 0x43, 0x0f, 0xdd, 0x26, 0x61, 0x96,
	0x6b, 0x2f, 0xd4, 0x59, 0xc9, 0x59, 0xf8, 0x29, 0x0b, 0x47, 0x83, 0xb5, 0xaf, 0xae, 0xd1, 0x97,
	0x70, 0xac, 0x4d, 0x2f, 0xa4, 0xde, 0xcb, 0x8f, 0x7e, 0x97, 0xd0, 0x45, 0x3f, 0x26, 0xd7, 0xbb,
	0x46, 0xab, 0xfe, 0x6a, 0x7f, 0xfb, 0xf5, 0x05, 0x3a, 0x13, 0xb5, 0x0a, 0xe3, 0xfd, 0x4f, 0x51,
	0x0d, 0xc2, 0xfe, 0x43, 0x10, 0x4f, 0x46, 0x3d, 0xd3, 0x43, 0x2d, 0x55, 0xb0, 0x0d, 0xa0, 0xc9,
	0xb1, 0xa6, 0x03, 0x20, 0x51, 0xb6, 0x2a, 0x24, 0x75, 0x49, 0x4f, 0xa1, 0xc1, 0x44, 0x2e, 0x70,
	0xf4, 0xee, 0xf9, 0xd1, 0x76, 0x7b, 0xbc, 0x52, 0x44, 0x5f, 0x71, 0x24, 0xb8, 0x53, 0xe8, 0x55,
	0x4f, 0xb5, 0xd4, 0xdc, 0x4c, 0xad, 0xcb, 0x9d, 0x2f, 0xea, 0x40, 0x9b, 0xab, 0xb5, 0xf4, 0x59,
	0xe6, 0x90, 0x21, 0x19, 0x11, 0x5e, 0x42, 0xf7, 0x0e, 0x06, 0x98, 0xe1, 0xbd, 0x8c, 0x37, 0x8f,
	0xa9, 0x2c, 0x77, 0xb3, 0x64, 0x5b, 0x35, 0xf6, 0xde, 0x48, 0x6f, 0x0b, 0x25, 0xcd, 0xad, 0x6c,
	0x80, 0xe1, 0x5b, 0x75, 0x3e, 0x3d, 0x86, 0xd6, 0x56, 0xb6, 0x50, 0x2a, 0x90, 0x2b, 0xe0, 0xd0,
	0xe8, 0xcc, 0xe4, 0xaf, 0x32, 0x95, 0x66, 0xed, 0x7a, 0xb3, 0xfa, 0x5d, 0xb5, 0x90, 0xcf, 0x30,
	0x56, 0xc2, 0x4b, 0x78, 0x0d, 0xcf, 0x1d, 0xcf, 0x3b, 0x4b, 0x16, 0x57, 0xc9, 0x62, 0xd1, 0xc2,
	0xa8, 0x2f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xd1, 0x5b, 0xbf, 0xbe, 0x03, 0x00, 0x00,
}
