// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: admin.entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *AdminCreateReq) Reset() {
	*x = AdminCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateReq) ProtoMessage() {}

func (x *AdminCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateReq.ProtoReflect.Descriptor instead.
func (*AdminCreateReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{0}
}

func (x *AdminCreateReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminCreateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type AdminUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name"`
	// @gotags: json:"password"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *AdminUpdateReq) Reset() {
	*x = AdminUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateReq) ProtoMessage() {}

func (x *AdminUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUpdateReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AdminUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminUpdateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type AdminListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	// @gotags: form:"name"
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
}

func (x *AdminListReq) Reset() {
	*x = AdminListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListReq) ProtoMessage() {}

func (x *AdminListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListReq.ProtoReflect.Descriptor instead.
func (*AdminListReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{2}
}

func (x *AdminListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminListReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type AdminDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *AdminDelReq) Reset() {
	*x = AdminDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDelReq) ProtoMessage() {}

func (x *AdminDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDelReq.ProtoReflect.Descriptor instead.
func (*AdminDelReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDelReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AdminDelReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type CheckPwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"account" binding:"required"
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"account" binding:"required"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"password" binding:"required"`
}

func (x *CheckPwdReq) Reset() {
	*x = CheckPwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPwdReq) ProtoMessage() {}

func (x *CheckPwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPwdReq.ProtoReflect.Descriptor instead.
func (*CheckPwdReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPwdReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CheckPwdReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminMenuTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"account" binding:"required"
	UID int64 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty" form:"account" binding:"required"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
}

func (x *AdminMenuTreeReq) Reset() {
	*x = AdminMenuTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminMenuTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMenuTreeReq) ProtoMessage() {}

func (x *AdminMenuTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMenuTreeReq.ProtoReflect.Descriptor instead.
func (*AdminMenuTreeReq) Descriptor() ([]byte, []int) {
	return file_admin_entity_proto_rawDescGZIP(), []int{5}
}

func (x *AdminMenuTreeReq) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *AdminMenuTreeReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

var File_admin_entity_proto protoreflect.FileDescriptor

var file_admin_entity_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x22, 0x6c, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x22, 0x6e, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x22, 0x39, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x0b,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_entity_proto_rawDescOnce sync.Once
	file_admin_entity_proto_rawDescData = file_admin_entity_proto_rawDesc
)

func file_admin_entity_proto_rawDescGZIP() []byte {
	file_admin_entity_proto_rawDescOnce.Do(func() {
		file_admin_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_entity_proto_rawDescData)
	})
	return file_admin_entity_proto_rawDescData
}

var file_admin_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_entity_proto_goTypes = []interface{}{
	(*AdminCreateReq)(nil),   // 0: proto.AdminCreateReq
	(*AdminUpdateReq)(nil),   // 1: proto.AdminUpdateReq
	(*AdminListReq)(nil),     // 2: proto.AdminListReq
	(*AdminDelReq)(nil),      // 3: proto.AdminDelReq
	(*CheckPwdReq)(nil),      // 4: proto.CheckPwdReq
	(*AdminMenuTreeReq)(nil), // 5: proto.AdminMenuTreeReq
}
var file_admin_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_entity_proto_init() }
func file_admin_entity_proto_init() {
	if File_admin_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminMenuTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_entity_proto_goTypes,
		DependencyIndexes: file_admin_entity_proto_depIdxs,
		MessageInfos:      file_admin_entity_proto_msgTypes,
	}.Build()
	File_admin_entity_proto = out.File
	file_admin_entity_proto_rawDesc = nil
	file_admin_entity_proto_goTypes = nil
	file_admin_entity_proto_depIdxs = nil
}
