// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain.entity.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DomainCreateReq struct {
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"domain" binding:"required"
	Domain string `protobuf:"bytes,2,opt,name=Domain,proto3" json:"domain" binding:"required"`
	// @gotags: json:"status" binding:"required"
	Status               int32    `protobuf:"varint,3,opt,name=Status,proto3" json:"status" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainCreateReq) Reset()         { *m = DomainCreateReq{} }
func (m *DomainCreateReq) String() string { return proto.CompactTextString(m) }
func (*DomainCreateReq) ProtoMessage()    {}
func (*DomainCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97ff0ea79ac626c, []int{0}
}

func (m *DomainCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainCreateReq.Unmarshal(m, b)
}
func (m *DomainCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainCreateReq.Marshal(b, m, deterministic)
}
func (m *DomainCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainCreateReq.Merge(m, src)
}
func (m *DomainCreateReq) XXX_Size() int {
	return xxx_messageInfo_DomainCreateReq.Size(m)
}
func (m *DomainCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_DomainCreateReq proto.InternalMessageInfo

func (m *DomainCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainCreateReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DomainCreateReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type DomainListReq struct {
	// @gotags: form:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"domain"
	Domain string `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty" form:"domain"`
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page                 int64    `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainListReq) Reset()         { *m = DomainListReq{} }
func (m *DomainListReq) String() string { return proto.CompactTextString(m) }
func (*DomainListReq) ProtoMessage()    {}
func (*DomainListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97ff0ea79ac626c, []int{1}
}

func (m *DomainListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainListReq.Unmarshal(m, b)
}
func (m *DomainListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainListReq.Marshal(b, m, deterministic)
}
func (m *DomainListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainListReq.Merge(m, src)
}
func (m *DomainListReq) XXX_Size() int {
	return xxx_messageInfo_DomainListReq.Size(m)
}
func (m *DomainListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainListReq.DiscardUnknown(m)
}

var xxx_messageInfo_DomainListReq proto.InternalMessageInfo

func (m *DomainListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainListReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DomainListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DomainListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type DomainDelReq struct {
	// @gotags: form:"name" json:"name" binding:"required"
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"name" form:"name" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainDelReq) Reset()         { *m = DomainDelReq{} }
func (m *DomainDelReq) String() string { return proto.CompactTextString(m) }
func (*DomainDelReq) ProtoMessage()    {}
func (*DomainDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97ff0ea79ac626c, []int{2}
}

func (m *DomainDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainDelReq.Unmarshal(m, b)
}
func (m *DomainDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainDelReq.Marshal(b, m, deterministic)
}
func (m *DomainDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainDelReq.Merge(m, src)
}
func (m *DomainDelReq) XXX_Size() int {
	return xxx_messageInfo_DomainDelReq.Size(m)
}
func (m *DomainDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DomainDelReq proto.InternalMessageInfo

func (m *DomainDelReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DomainUpdateReq struct {
	// @gotags: json:"id"  binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"domain" binding:"required"
	Domain string `protobuf:"bytes,3,opt,name=Domain,proto3" json:"domain" binding:"required"`
	// @gotags: json:"status" binding:"required"
	Status               int32    `protobuf:"varint,4,opt,name=Status,proto3" json:"status" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainUpdateReq) Reset()         { *m = DomainUpdateReq{} }
func (m *DomainUpdateReq) String() string { return proto.CompactTextString(m) }
func (*DomainUpdateReq) ProtoMessage()    {}
func (*DomainUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97ff0ea79ac626c, []int{3}
}

func (m *DomainUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainUpdateReq.Unmarshal(m, b)
}
func (m *DomainUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainUpdateReq.Marshal(b, m, deterministic)
}
func (m *DomainUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainUpdateReq.Merge(m, src)
}
func (m *DomainUpdateReq) XXX_Size() int {
	return xxx_messageInfo_DomainUpdateReq.Size(m)
}
func (m *DomainUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_DomainUpdateReq proto.InternalMessageInfo

func (m *DomainUpdateReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DomainUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainUpdateReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DomainUpdateReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*DomainCreateReq)(nil), "proto.DomainCreateReq")
	proto.RegisterType((*DomainListReq)(nil), "proto.DomainListReq")
	proto.RegisterType((*DomainDelReq)(nil), "proto.DomainDelReq")
	proto.RegisterType((*DomainUpdateReq)(nil), "proto.DomainUpdateReq")
}

func init() { proto.RegisterFile("domain.entity.proto", fileDescriptor_a97ff0ea79ac626c) }

var fileDescriptor_a97ff0ea79ac626c = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xc9, 0xcf, 0x4d,
	0xcc, 0xcc, 0xd3, 0x4b, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x53, 0x4a, 0xa1, 0x5c, 0xfc, 0x2e, 0x60, 0x59, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4,
	0xa0, 0xd4, 0x42, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0x5b, 0x48, 0x8c, 0x8b, 0x0d, 0xa2, 0x4c, 0x82, 0x09, 0x2c, 0x0a, 0xe5, 0x81,
	0xc4, 0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c,
	0xa5, 0x6c, 0x2e, 0x5e, 0x88, 0x0a, 0x9f, 0xcc, 0xe2, 0x12, 0x52, 0x0d, 0x95, 0xe2, 0xe2, 0x08,
	0x48, 0x4c, 0x4f, 0x0d, 0xce, 0xac, 0x4a, 0x05, 0x1b, 0xcb, 0x1c, 0x04, 0xe7, 0x83, 0xcc, 0x01,
	0xb1, 0x25, 0x58, 0xc0, 0xe2, 0x60, 0xb6, 0x92, 0x1c, 0x17, 0x0f, 0x44, 0xa7, 0x4b, 0x6a, 0x0e,
	0xc8, 0x2e, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0xb0, 0x4d, 0xcc, 0x41, 0x4c, 0x9e, 0x2e, 0x4a, 0xa9,
	0x30, 0x3f, 0x86, 0x16, 0xa4, 0x40, 0xfd, 0x88, 0xa6, 0x04, 0xee, 0x3c, 0x26, 0xac, 0xce, 0x63,
	0xc6, 0xe1, 0x67, 0x16, 0x64, 0x3f, 0x3b, 0x71, 0x45, 0x71, 0xe8, 0xe9, 0xe9, 0x17, 0x24, 0x59,
	0x17, 0x24, 0x25, 0xb1, 0x81, 0x43, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x4a, 0x0c,
	0x17, 0x7b, 0x01, 0x00, 0x00,
}
