// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.entity.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PermissionListReq struct {
	// @gotags: from:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" from:"name"`
	// @gotags: from:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty" from:"page_size"`
	// @gotags: from:"page"
	Page int64 `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty" from:"page"`
	// @gotags: from:"domain_id"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" from:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionListReq) Reset()         { *m = PermissionListReq{} }
func (m *PermissionListReq) String() string { return proto.CompactTextString(m) }
func (*PermissionListReq) ProtoMessage()    {}
func (*PermissionListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{0}
}

func (m *PermissionListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionListReq.Unmarshal(m, b)
}
func (m *PermissionListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionListReq.Marshal(b, m, deterministic)
}
func (m *PermissionListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionListReq.Merge(m, src)
}
func (m *PermissionListReq) XXX_Size() int {
	return xxx_messageInfo_PermissionListReq.Size(m)
}
func (m *PermissionListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionListReq proto.InternalMessageInfo

func (m *PermissionListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PermissionListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PermissionListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PermissionListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type PermissionCreateReq struct {
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,2,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionCreateReq) Reset()         { *m = PermissionCreateReq{} }
func (m *PermissionCreateReq) String() string { return proto.CompactTextString(m) }
func (*PermissionCreateReq) ProtoMessage()    {}
func (*PermissionCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{1}
}

func (m *PermissionCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionCreateReq.Unmarshal(m, b)
}
func (m *PermissionCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionCreateReq.Marshal(b, m, deterministic)
}
func (m *PermissionCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionCreateReq.Merge(m, src)
}
func (m *PermissionCreateReq) XXX_Size() int {
	return xxx_messageInfo_PermissionCreateReq.Size(m)
}
func (m *PermissionCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionCreateReq proto.InternalMessageInfo

func (m *PermissionCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PermissionCreateReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PermissionCreateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type PermissionUpdateReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,3,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionUpdateReq) Reset()         { *m = PermissionUpdateReq{} }
func (m *PermissionUpdateReq) String() string { return proto.CompactTextString(m) }
func (*PermissionUpdateReq) ProtoMessage()    {}
func (*PermissionUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{2}
}

func (m *PermissionUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionUpdateReq.Unmarshal(m, b)
}
func (m *PermissionUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionUpdateReq.Marshal(b, m, deterministic)
}
func (m *PermissionUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionUpdateReq.Merge(m, src)
}
func (m *PermissionUpdateReq) XXX_Size() int {
	return xxx_messageInfo_PermissionUpdateReq.Size(m)
}
func (m *PermissionUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionUpdateReq proto.InternalMessageInfo

func (m *PermissionUpdateReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PermissionUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PermissionUpdateReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PermissionUpdateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type PermissionDelReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionDelReq) Reset()         { *m = PermissionDelReq{} }
func (m *PermissionDelReq) String() string { return proto.CompactTextString(m) }
func (*PermissionDelReq) ProtoMessage()    {}
func (*PermissionDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{3}
}

func (m *PermissionDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionDelReq.Unmarshal(m, b)
}
func (m *PermissionDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionDelReq.Marshal(b, m, deterministic)
}
func (m *PermissionDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionDelReq.Merge(m, src)
}
func (m *PermissionDelReq) XXX_Size() int {
	return xxx_messageInfo_PermissionDelReq.Size(m)
}
func (m *PermissionDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionDelReq proto.InternalMessageInfo

func (m *PermissionDelReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PermissionDelReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type PermissionPathListReq struct {
	// @gotags: form:"permission_id"
	PermissionID int64 `protobuf:"varint,1,opt,name=PermissionID,proto3" json:"PermissionID,omitempty" form:"permission_id"`
	// @gotags: form:"domain_id"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionPathListReq) Reset()         { *m = PermissionPathListReq{} }
func (m *PermissionPathListReq) String() string { return proto.CompactTextString(m) }
func (*PermissionPathListReq) ProtoMessage()    {}
func (*PermissionPathListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{4}
}

func (m *PermissionPathListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionPathListReq.Unmarshal(m, b)
}
func (m *PermissionPathListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionPathListReq.Marshal(b, m, deterministic)
}
func (m *PermissionPathListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionPathListReq.Merge(m, src)
}
func (m *PermissionPathListReq) XXX_Size() int {
	return xxx_messageInfo_PermissionPathListReq.Size(m)
}
func (m *PermissionPathListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionPathListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionPathListReq proto.InternalMessageInfo

func (m *PermissionPathListReq) GetPermissionID() int64 {
	if m != nil {
		return m.PermissionID
	}
	return 0
}

func (m *PermissionPathListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type PermissionPathSetReq struct {
	// @gotags: json:"permission_id"
	PermissionID int64 `protobuf:"varint,1,opt,name=PermissionID,proto3" json:"permission_id"`
	// @gotags: json:"path_ids" binding:"required"
	PathIDs []int64 `protobuf:"varint,2,rep,packed,name=PathIDs,proto3" json:"path_ids" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionPathSetReq) Reset()         { *m = PermissionPathSetReq{} }
func (m *PermissionPathSetReq) String() string { return proto.CompactTextString(m) }
func (*PermissionPathSetReq) ProtoMessage()    {}
func (*PermissionPathSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_10a0a08ebcc326dc, []int{5}
}

func (m *PermissionPathSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionPathSetReq.Unmarshal(m, b)
}
func (m *PermissionPathSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionPathSetReq.Marshal(b, m, deterministic)
}
func (m *PermissionPathSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionPathSetReq.Merge(m, src)
}
func (m *PermissionPathSetReq) XXX_Size() int {
	return xxx_messageInfo_PermissionPathSetReq.Size(m)
}
func (m *PermissionPathSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionPathSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionPathSetReq proto.InternalMessageInfo

func (m *PermissionPathSetReq) GetPermissionID() int64 {
	if m != nil {
		return m.PermissionID
	}
	return 0
}

func (m *PermissionPathSetReq) GetPathIDs() []int64 {
	if m != nil {
		return m.PathIDs
	}
	return nil
}

func (m *PermissionPathSetReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

func init() {
	proto.RegisterType((*PermissionListReq)(nil), "proto.PermissionListReq")
	proto.RegisterType((*PermissionCreateReq)(nil), "proto.PermissionCreateReq")
	proto.RegisterType((*PermissionUpdateReq)(nil), "proto.PermissionUpdateReq")
	proto.RegisterType((*PermissionDelReq)(nil), "proto.PermissionDelReq")
	proto.RegisterType((*PermissionPathListReq)(nil), "proto.PermissionPathListReq")
	proto.RegisterType((*PermissionPathSetReq)(nil), "proto.PermissionPathSetReq")
}

func init() { proto.RegisterFile("permission.entity.proto", fileDescriptor_10a0a08ebcc326dc) }

var fileDescriptor_10a0a08ebcc326dc = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0x87, 0x71, 0xc6, 0x6a, 0xf7, 0x11, 0x51, 0x53, 0xd1, 0xd0, 0x49, 0x3c, 0x79, 0xb2, 0x43,
	0xc7, 0xa0, 0x43, 0xcd, 0x45, 0x88, 0x90, 0x59, 0x22, 0xea, 0x36, 0xd6, 0xa3, 0x06, 0x52, 0x27,
	0x67, 0x2e, 0xf5, 0xd7, 0x87, 0x53, 0xea, 0x2a, 0xbb, 0xd2, 0xc9, 0xf7, 0xc6, 0xf7, 0xfb, 0x3e,
	0x7d, 0x0c, 0x9c, 0x19, 0x6c, 0x4a, 0x6d, 0xad, 0xae, 0xab, 0x14, 0x2b, 0xa7, 0xdd, 0x57, 0x6a,
	0x9a, 0xda, 0xd5, 0x6c, 0xc7, 0x3f, 0x62, 0x0b, 0x47, 0x79, 0x3f, 0x71, 0xa7, 0xad, 0x93, 0xf8,
	0xc9, 0x18, 0x84, 0xf7, 0xaa, 0x44, 0x1e, 0x44, 0x41, 0xb2, 0x94, 0xbe, 0x66, 0xe7, 0xb0, 0xc8,
	0xd5, 0x1b, 0xae, 0xf4, 0x37, 0x72, 0x12, 0x05, 0x09, 0x95, 0x7d, 0xdf, 0xce, 0xb7, 0x35, 0xa7,
	0xfe, 0xdc, 0xd7, 0xed, 0xbc, 0xa8, 0x4b, 0xa5, 0xab, 0x4c, 0xf0, 0xf0, 0x77, 0xbe, 0xeb, 0xe3,
	0x27, 0x38, 0x1e, 0xa4, 0xb7, 0x0d, 0x2a, 0x87, 0xdb, 0xb4, 0x0c, 0x42, 0x81, 0xf6, 0xc5, 0x2b,
	0x97, 0xd2, 0xd7, 0x23, 0x34, 0x9d, 0xa0, 0xf5, 0x3a, 0xfa, 0xc1, 0xbc, 0xfe, 0xa1, 0x0f, 0x80,
	0x64, 0xc2, 0x83, 0xa9, 0x24, 0x99, 0xe8, 0x55, 0x64, 0x83, 0x8a, 0x6e, 0x51, 0x4d, 0xff, 0xe2,
	0x1a, 0x0e, 0x07, 0x95, 0xc0, 0x8f, 0x4d, 0x9e, 0xf5, 0x3c, 0x99, 0xe4, 0x1f, 0xe1, 0x74, 0xc8,
	0xe7, 0xca, 0xbd, 0x77, 0xeb, 0x8f, 0x61, 0x7f, 0x78, 0xd1, 0xe3, 0x46, 0x67, 0xb3, 0x1f, 0x66,
	0xe0, 0x64, 0x0c, 0x5e, 0xe1, 0xbf, 0xb9, 0x1c, 0xf6, 0xda, 0x44, 0x26, 0x2c, 0x27, 0x11, 0x4d,
	0xa8, 0xec, 0xda, 0xb9, 0xad, 0xdf, 0xc0, 0xf3, 0x22, 0x4d, 0x2f, 0x4c, 0x71, 0x65, 0x8a, 0x62,
	0xd7, 0x5f, 0xac, 0xcb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x59, 0x75, 0xb4, 0x7a, 0x02,
	0x00, 0x00,
}
