// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: role.entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page int64 `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
}

func (x *RoleListReq) Reset() {
	*x = RoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReq) ProtoMessage() {}

func (x *RoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReq.ProtoReflect.Descriptor instead.
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{0}
}

func (x *RoleListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoleListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RoleListReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type RoleCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,2,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *RoleCreateReq) Reset() {
	*x = RoleCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateReq) ProtoMessage() {}

func (x *RoleCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateReq.ProtoReflect.Descriptor instead.
func (*RoleCreateReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{1}
}

func (x *RoleCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleCreateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RoleCreateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type RoleUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,3,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *RoleUpdateReq) Reset() {
	*x = RoleUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUpdateReq) ProtoMessage() {}

func (x *RoleUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUpdateReq.ProtoReflect.Descriptor instead.
func (*RoleUpdateReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{2}
}

func (x *RoleUpdateReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RoleUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleUpdateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RoleUpdateReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type RoleDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *RoleDelReq) Reset() {
	*x = RoleDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDelReq) ProtoMessage() {}

func (x *RoleDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDelReq.ProtoReflect.Descriptor instead.
func (*RoleDelReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{3}
}

func (x *RoleDelReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RoleDelReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type RolePermissionListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: form:"role_id" binding:"required"
	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty" form:"role_id" binding:"required"`
	// @gotags: form:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id" binding:"required"`
}

func (x *RolePermissionListReq) Reset() {
	*x = RolePermissionListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionListReq) ProtoMessage() {}

func (x *RolePermissionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionListReq.ProtoReflect.Descriptor instead.
func (*RolePermissionListReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{4}
}

func (x *RolePermissionListReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RolePermissionListReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

type RolePermissionSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"role_id" binding:"required"
	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"role_id" binding:"required"`
	// @gotags: json:"permission_ids" binding:"required"
	PermissionIDS []int64 `protobuf:"varint,2,rep,packed,name=PermissionIDS,proto3" json:"permission_ids" binding:"required"`
	// @gotags: json:"domain_id" binding:"required"
	DomainID int64 `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id" binding:"required"`
}

func (x *RolePermissionSetReq) Reset() {
	*x = RolePermissionSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionSetReq) ProtoMessage() {}

func (x *RolePermissionSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionSetReq.ProtoReflect.Descriptor instead.
func (*RolePermissionSetReq) Descriptor() ([]byte, []int) {
	return file_role_entity_proto_rawDescGZIP(), []int{5}
}

func (x *RolePermissionSetReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RolePermissionSetReq) GetPermissionIDS() []int64 {
	if x != nil {
		return x.PermissionIDS
	}
	return nil
}

func (x *RolePermissionSetReq) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

var File_role_entity_proto protoreflect.FileDescriptor

var file_role_entity_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x53, 0x0a, 0x0d, 0x52, 0x6f, 0x6c,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x63,
	0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x4b, 0x0a,
	0x15, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x70, 0x0a, 0x14, 0x52, 0x6f,
	0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x53, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x53,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_role_entity_proto_rawDescOnce sync.Once
	file_role_entity_proto_rawDescData = file_role_entity_proto_rawDesc
)

func file_role_entity_proto_rawDescGZIP() []byte {
	file_role_entity_proto_rawDescOnce.Do(func() {
		file_role_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_entity_proto_rawDescData)
	})
	return file_role_entity_proto_rawDescData
}

var file_role_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_role_entity_proto_goTypes = []interface{}{
	(*RoleListReq)(nil),           // 0: proto.RoleListReq
	(*RoleCreateReq)(nil),         // 1: proto.RoleCreateReq
	(*RoleUpdateReq)(nil),         // 2: proto.RoleUpdateReq
	(*RoleDelReq)(nil),            // 3: proto.RoleDelReq
	(*RolePermissionListReq)(nil), // 4: proto.RolePermissionListReq
	(*RolePermissionSetReq)(nil),  // 5: proto.RolePermissionSetReq
}
var file_role_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_entity_proto_init() }
func file_role_entity_proto_init() {
	if File_role_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_role_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePermissionListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePermissionSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_entity_proto_goTypes,
		DependencyIndexes: file_role_entity_proto_depIdxs,
		MessageInfos:      file_role_entity_proto_msgTypes,
	}.Build()
	File_role_entity_proto = out.File
	file_role_entity_proto_rawDesc = nil
	file_role_entity_proto_goTypes = nil
	file_role_entity_proto_depIdxs = nil
}
