// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.entity.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleListReq struct {
	// @gotags: form:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" form:"name"`
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty" form:"page_size"`
	// @gotags: form:"page"
	Page int64 `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty" form:"page"`
	// @gotags: form:"domain_id"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleListReq) Reset()         { *m = RoleListReq{} }
func (m *RoleListReq) String() string { return proto.CompactTextString(m) }
func (*RoleListReq) ProtoMessage()    {}
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{0}
}

func (m *RoleListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListReq.Unmarshal(m, b)
}
func (m *RoleListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListReq.Marshal(b, m, deterministic)
}
func (m *RoleListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListReq.Merge(m, src)
}
func (m *RoleListReq) XXX_Size() int {
	return xxx_messageInfo_RoleListReq.Size(m)
}
func (m *RoleListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListReq proto.InternalMessageInfo

func (m *RoleListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *RoleListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RoleListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RoleCreateReq struct {
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,2,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleCreateReq) Reset()         { *m = RoleCreateReq{} }
func (m *RoleCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoleCreateReq) ProtoMessage()    {}
func (*RoleCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{1}
}

func (m *RoleCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateReq.Unmarshal(m, b)
}
func (m *RoleCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateReq.Marshal(b, m, deterministic)
}
func (m *RoleCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateReq.Merge(m, src)
}
func (m *RoleCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoleCreateReq.Size(m)
}
func (m *RoleCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateReq proto.InternalMessageInfo

func (m *RoleCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleCreateReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RoleCreateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RoleUpdateReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"name" binding:"required"`
	// @gotags: json:"desc" binding:"required"
	Desc string `protobuf:"bytes,3,opt,name=Desc,proto3" json:"desc" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,4,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleUpdateReq) Reset()         { *m = RoleUpdateReq{} }
func (m *RoleUpdateReq) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateReq) ProtoMessage()    {}
func (*RoleUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{2}
}

func (m *RoleUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateReq.Unmarshal(m, b)
}
func (m *RoleUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateReq.Marshal(b, m, deterministic)
}
func (m *RoleUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateReq.Merge(m, src)
}
func (m *RoleUpdateReq) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateReq.Size(m)
}
func (m *RoleUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateReq proto.InternalMessageInfo

func (m *RoleUpdateReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoleUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleUpdateReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RoleUpdateReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RoleDelReq struct {
	// @gotags: json:"id" binding:"required"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDelReq) Reset()         { *m = RoleDelReq{} }
func (m *RoleDelReq) String() string { return proto.CompactTextString(m) }
func (*RoleDelReq) ProtoMessage()    {}
func (*RoleDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{3}
}

func (m *RoleDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDelReq.Unmarshal(m, b)
}
func (m *RoleDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDelReq.Marshal(b, m, deterministic)
}
func (m *RoleDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDelReq.Merge(m, src)
}
func (m *RoleDelReq) XXX_Size() int {
	return xxx_messageInfo_RoleDelReq.Size(m)
}
func (m *RoleDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDelReq proto.InternalMessageInfo

func (m *RoleDelReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoleDelReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RolePermissionListReq struct {
	// @gotags: form:"role_id"
	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty" form:"role_id"`
	// @gotags: form:"domain_id"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePermissionListReq) Reset()         { *m = RolePermissionListReq{} }
func (m *RolePermissionListReq) String() string { return proto.CompactTextString(m) }
func (*RolePermissionListReq) ProtoMessage()    {}
func (*RolePermissionListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{4}
}

func (m *RolePermissionListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermissionListReq.Unmarshal(m, b)
}
func (m *RolePermissionListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermissionListReq.Marshal(b, m, deterministic)
}
func (m *RolePermissionListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermissionListReq.Merge(m, src)
}
func (m *RolePermissionListReq) XXX_Size() int {
	return xxx_messageInfo_RolePermissionListReq.Size(m)
}
func (m *RolePermissionListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermissionListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermissionListReq proto.InternalMessageInfo

func (m *RolePermissionListReq) GetRoleID() int64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *RolePermissionListReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RolePermissionReq struct {
	// @gotags: form:"role_id"
	RoleIDs []int64 `protobuf:"varint,1,rep,packed,name=RoleIDs,proto3" json:"RoleIDs,omitempty" form:"role_id"`
	// @gotags: form:"domain_id"
	DomainID             int64    `protobuf:"varint,2,opt,name=DomainID,proto3" json:"DomainID,omitempty" form:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePermissionReq) Reset()         { *m = RolePermissionReq{} }
func (m *RolePermissionReq) String() string { return proto.CompactTextString(m) }
func (*RolePermissionReq) ProtoMessage()    {}
func (*RolePermissionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{5}
}

func (m *RolePermissionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermissionReq.Unmarshal(m, b)
}
func (m *RolePermissionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermissionReq.Marshal(b, m, deterministic)
}
func (m *RolePermissionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermissionReq.Merge(m, src)
}
func (m *RolePermissionReq) XXX_Size() int {
	return xxx_messageInfo_RolePermissionReq.Size(m)
}
func (m *RolePermissionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermissionReq.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermissionReq proto.InternalMessageInfo

func (m *RolePermissionReq) GetRoleIDs() []int64 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

func (m *RolePermissionReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

type RolePermissionSetReq struct {
	// @gotags: json:"role_id" binding:"required"
	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"role_id" binding:"required"`
	// @gotags: json:"permission_ids" binding:"required"
	PermissionIDS []int64 `protobuf:"varint,2,rep,packed,name=PermissionIDS,proto3" json:"permission_ids" binding:"required"`
	// @gotags: json:"domain_id"
	DomainID             int64    `protobuf:"varint,3,opt,name=DomainID,proto3" json:"domain_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePermissionSetReq) Reset()         { *m = RolePermissionSetReq{} }
func (m *RolePermissionSetReq) String() string { return proto.CompactTextString(m) }
func (*RolePermissionSetReq) ProtoMessage()    {}
func (*RolePermissionSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb0823aacbe0a6d, []int{6}
}

func (m *RolePermissionSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermissionSetReq.Unmarshal(m, b)
}
func (m *RolePermissionSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermissionSetReq.Marshal(b, m, deterministic)
}
func (m *RolePermissionSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermissionSetReq.Merge(m, src)
}
func (m *RolePermissionSetReq) XXX_Size() int {
	return xxx_messageInfo_RolePermissionSetReq.Size(m)
}
func (m *RolePermissionSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermissionSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermissionSetReq proto.InternalMessageInfo

func (m *RolePermissionSetReq) GetRoleID() int64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *RolePermissionSetReq) GetPermissionIDS() []int64 {
	if m != nil {
		return m.PermissionIDS
	}
	return nil
}

func (m *RolePermissionSetReq) GetDomainID() int64 {
	if m != nil {
		return m.DomainID
	}
	return 0
}

func init() {
	proto.RegisterType((*RoleListReq)(nil), "proto.RoleListReq")
	proto.RegisterType((*RoleCreateReq)(nil), "proto.RoleCreateReq")
	proto.RegisterType((*RoleUpdateReq)(nil), "proto.RoleUpdateReq")
	proto.RegisterType((*RoleDelReq)(nil), "proto.RoleDelReq")
	proto.RegisterType((*RolePermissionListReq)(nil), "proto.RolePermissionListReq")
	proto.RegisterType((*RolePermissionReq)(nil), "proto.RolePermissionReq")
	proto.RegisterType((*RolePermissionSetReq)(nil), "proto.RolePermissionSetReq")
}

func init() { proto.RegisterFile("role.entity.proto", fileDescriptor_fcb0823aacbe0a6d) }

var fileDescriptor_fcb0823aacbe0a6d = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4f, 0x83, 0x30,
	0x14, 0x87, 0x43, 0x3b, 0xe7, 0xf6, 0xcc, 0x4c, 0x46, 0xd4, 0x34, 0x9e, 0xc8, 0xe2, 0x81, 0x13,
	0x1e, 0xbc, 0x98, 0x78, 0xd3, 0x5e, 0x88, 0xc6, 0x2c, 0x25, 0x5e, 0xbc, 0xc1, 0x7c, 0x31, 0x4d,
	0x80, 0x56, 0xda, 0x8b, 0xfe, 0xf5, 0xa6, 0x65, 0xa0, 0x90, 0x8d, 0x13, 0xef, 0x95, 0xf7, 0xfb,
	0xbe, 0x17, 0x28, 0xac, 0x1b, 0x55, 0x62, 0x82, 0xb5, 0x95, 0xf6, 0x3b, 0xd1, 0x8d, 0xb2, 0x2a,
	0x3c, 0xf1, 0x8f, 0x4d, 0x05, 0x67, 0x42, 0x95, 0xf8, 0x22, 0x8d, 0x15, 0xf8, 0x15, 0x86, 0x30,
	0x7b, 0xcd, 0x2b, 0x64, 0x41, 0x14, 0xc4, 0x4b, 0xe1, 0xeb, 0xf0, 0x1a, 0x16, 0xdb, 0xfc, 0x13,
	0x33, 0xf9, 0x83, 0x8c, 0x44, 0x41, 0x4c, 0x45, 0xdf, 0xbb, 0x79, 0x57, 0x33, 0xea, 0xcf, 0x7d,
	0xed, 0xe6, 0xb9, 0xaa, 0x72, 0x59, 0xa7, 0x9c, 0xcd, 0xda, 0xf9, 0xae, 0xdf, 0x64, 0xb0, 0x72,
	0xba, 0xa7, 0x06, 0x73, 0x8b, 0xc7, 0x84, 0x21, 0xcc, 0x38, 0x9a, 0x9d, 0x97, 0x2d, 0x85, 0xaf,
	0x07, 0x50, 0x3a, 0x82, 0xee, 0x5a, 0xe8, 0x9b, 0xfe, 0xd8, 0x43, 0xcf, 0x81, 0xa4, 0xdc, 0x23,
	0xa9, 0x20, 0x29, 0xef, 0x25, 0xe4, 0x80, 0x84, 0x1e, 0x91, 0x8c, 0x37, 0xbf, 0x07, 0x70, 0x12,
	0x8e, 0xe5, 0x21, 0xc3, 0xff, 0x24, 0x19, 0x25, 0x9f, 0xe1, 0xd2, 0x25, 0xb7, 0xd8, 0x54, 0xd2,
	0x18, 0xa9, 0xea, 0xee, 0x63, 0x5f, 0xc1, 0xdc, 0xbd, 0xe8, 0x41, 0xfb, 0x6e, 0x12, 0x96, 0xc2,
	0x7a, 0x08, 0x73, 0x20, 0x06, 0xa7, 0x6d, 0xd4, 0xb0, 0x20, 0xa2, 0x31, 0x15, 0x5d, 0x3b, 0x89,
	0xd2, 0x70, 0x31, 0x44, 0x65, 0x38, 0xb9, 0xd6, 0x0d, 0xac, 0xfe, 0x66, 0x53, 0x9e, 0x31, 0xe2,
	0x5d, 0xc3, 0xc3, 0xa9, 0x1f, 0xf5, 0x08, 0xef, 0x8b, 0x24, 0xb9, 0xd5, 0xc5, 0x83, 0x2e, 0x8a,
	0xb9, 0xbf, 0x7f, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0x09, 0x8b, 0xc3, 0x9b, 0x02,
	0x00, 0x00,
}
